### ISSUE TITLE
Running All Protocols on port 443 and also adguard home dns dns over https at port 443?

### ISSUE THREAD

**Issue by t-e-s-tweb** [jinwyp/one_click_script#162]
Can you please give the recommended flow for adding all protocols one by one or combined at port 443 and also being able to run adguard on 443 for doh service?

**Comment by jinwyp** [comment]
1  I recommended install adguard home on a separate server. Because adguard home require more CPU and memory  to resovle DNS request

2 Install adguard home and xray/ trojan on same server :   Step 1 install adguard home first, Step 2 install xray/trojan using non 443 port. And Don't install Nginx .  Because adguard home will serve 443 for TLS and DOH

3 Install All Protocols on port 443:  Step 1 Choose 12 or 23 to install nginx and v2ray/xray  Step 2 install adguard home 
Step 3 modify /etc/nginx/nginx.conf  to  reverse proxy adguard home .


https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#nginx
https://github.com/AdguardTeam/AdGuardHome/issues/4266


There are two important settings: One is reverse proxy for adguard home UI . 

```
location /aghome/ {
    proxy_pass http://AGH_IP:AGH_PORT/;
    proxy_redirect / /aghome/;
    proxy_cookie_path / /aghome/;
}
```

The other settings  is serve DOH by Nginx.  Need to disable DoH encryption on AdGuard Home. 

When you use TLS on your reverse proxy server, there's no need to use TLS on AdGuard Home. Set allow_unencrypted_doh: true in AdGuardHome.yaml to allow AdGuard Home respond to DoH requests without TLS encryption.
